# Generated by Django 5.2.7 on 2025-11-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
    ]
